# Starts 3D fused pointcloud generation, if not automatically enabled with the parameter `mapping/mapping_enabled`

# Resolution of the fused pointcloud in meters [0.01, 0.2]
float32 resolution

# Max mapping range in meters [0.2, 20.0]
float32 max_mapping_range

# Frequency of the publishing of the fused colored point cloud
float32 fused_pointcloud_freq

---
bool done
