# Starts object detection, if not automatically enabled with the parameter `object_detection/od_enabled`

# OD Model
# '0': MULTI_CLASS_BOX - '1': MULTI_CLASS_BOX_ACCURATE - '2': HUMAN_BODY_FAST - '3': HUMAN_BODY_ACCURATE
int8 model

# Minimum Confidence level
float32 confidence

# MAx detection range
float32 max_range

# Object tracking
bool tracking

# Body Fitting
bool sk_body_fitting

# Detect people (valid for Multi-class model)
bool mc_people

# Detect vehicles
bool mc_vehicles

# Detect bags
bool mc_bag

# Detect animals
bool mc_animal

# Detect electronic devices
bool mc_electronics

# Detect fruits and vegetables
bool mc_fruit_vegetable

---
bool done
